version: "3.7"

services:
  
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_ROOT_PASSWORD=toor
          - MYSQL_DATABASE=projet_trenta
          - MYSQL_USER=projet_trenta
          - MYSQL_PASSWORD=projet_trenta
        volumes: 
          - mysql-data:/var/lib/mysql
        ports:
          - 3306:3306
        networks:
          - db

    adminer:
        image: adminer
        ports:
          - 8080:8080
        networks:
          - db

    nginx:
        image: nginx:1.17
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./:/var/www/html
        networks:
          - app
        configs:
          - source: nginx_config
            target: /etc/nginx/conf.d/default.conf

    php:
        image: projet_trenta_php:7.2
        ports:
          - 9000:9000
        volumes:
          - ./:/var/www/html
        networks:
          - app
          - db
        configs:
          - source: php_config
            target: /usr/local/etc/php/php.ini  


volumes:
  mysql-data:

configs:
  nginx_config:
    file: ./conf/nginx.conf
  php_config:
    file: ./conf/php.ini

networks:
  db:
  app: